### ISSUE TITLE
Instructions in step 7 need to be updated

### ISSUE THREAD

**Issue by majamanojlovic** [raspberrypilearning/mystery-letter#38]
Volunteer feedback:

_Click on the + "Select this font" button:_

_A message saying "1 Family Selected" will appear at the bottom on the screen._

_Click on the "1 Family Selected" message to open the window and copy the highlighted code:_

_Return to Google fonts and scroll further down the page and copy the font-family code:_

Google fonts webpage has changed so these should be updated. Probably images as well.

**Comment by libxx1** [comment]
Made changes to draft to reflect process. Waiting for answer to this o/s query before pushing to master. 

We use Google fonts in Mystery Letter. The new Google fonts website gives the code to embed as:

"<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">"

The old code we used to embed from Google Fonts was:

"<link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">.

The new code works but with an error. Should we tell people to delete the '&display=swap' (the bit causing the error) and , are we ok with getting them to add the additional <link rel="preconnect" href="https://fonts.gstatic.com">  and using 'css2' ?
